@url_dev=http://localhost:3052/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: a94baea875d251ea049827251bb992e5

{
    "name": "shop name 2",
    "email": "shop02@example.com",
    "password": "shop_password"
}
